In [1]:
import pandas as pd
import numpy as np

In [2]:
ec = pd.read_csv('ecommerce_customer_behavior.csv')
ec

,Time_on_site,Pages_viewed,Clicked_ad,Cart_value,Referral,Browser_Refresh_Rate,Last_Ad_Seen,Purchase
0,2.29,5.37,1,10.00,Facebook,143.14,D,1
1,7.49,16.36,0,25.52,Instagram,136.66,A,1
2,5.71,13.69,0,10.00,Google,67.13,C,0
3,1.23,3.22,1,41.49,Google,92.12,C,0
4,3.55,10.72,0,21.57,Direct,70.31,B,0
...,...,...,...,...,...,...,...,...
2245,2.32,5.81,1,24.87,Google,65.37,D,0
2246,6.76,13.60,0,21.42,Facebook,92.84,A,0
2247,3.78,10.62,0,50.71,Google,148.14,A,0
2248,3.84,8.17,1,30.11,Instagram,43.91,C,0
2249,4.30,10.24,0,145.32,Google,132.46,B,0

In [10]:
num_rows = ec.shape[0]
ec['ID'] = np.random.randint(1, 300, size=num_rows)
date_range = pd.date_range(start='2025-01-01', end='2025-07-31')

ec['Date_Accessed'] = np.random.choice(date_range, size=num_rows)
ec.to_csv('ecommerce_cust_behavior.csv', index=False)

In [13]:
ec2 = pd.read_csv('ecommerce_cust_behavior.csv')
platform_map = {
    'Google': 1,
    'Facebook': 2,
    'Instagram': 3,
    'Direct': 4
}


ec2['Platform_Num'] = ec2['Referral'].map(platform_map)

ec2.to_csv('Cust_Behavior_Final.csv', index=False)

print(ec2.head())

   Time_on_site  Pages_viewed  Clicked_ad  Cart_value   Referral  \
0          2.29          5.37           1       10.00   Facebook
1          7.49         16.36           0       25.52  Instagram
2          5.71         13.69           0       10.00     Google
3          1.23          3.22           1       41.49     Google
4          3.55         10.72           0       21.57     Direct

   Browser_Refresh_Rate Last_Ad_Seen  Purchase   ID Date_Accessed  \
0                143.14            D         1   71    2025-03-27
1                136.66            A         1  193    2025-07-21
2                 67.13            C         0  121    2025-02-21
3                 92.12            C         0  240    2025-05-03
4                 70.31            B         0  287    2025-04-28

   Platform_Num
0             2
1             3
2             1
3             1
4             4

In [4]:
data = {
    'Platform': ['Google', 'Facebook', 'Instagram', 'Direct'],
    'Average CPC': [0.63, 0.70, 0.55, 1.00]
}
cpc = pd.DataFrame(data)
cpc.to_csv('cpc_table.csv', index=False)
print(cpc)

    Platform  Average CPC
0     Google         0.63
1   Facebook         0.70
2  Instagram         0.55
3     Direct         1.00

In [12]:
df = pd.DataFrame(data)

platform_map = {
    'Google': 1,
    'Facebook': 2,
    'Instagram': 3,
    'Direct': 4
}

df['Plat_Num'] = df['Platform'].map(platform_map)

df.to_csv('cpc_table_updated.csv', index=False)

print(df)

    Platform  Average CPC  Plat_Num
0     Google         0.63         1
1   Facebook         0.70         2
2  Instagram         0.55         3
3     Direct         1.00         4